export const questions = [
    { text: "O seu parceiro(a) controla as suas decisões?", context: "Se alguém impede que tome decisões pessoais, isso pode ser um sinal de abuso psicológico." },
    { text: "Ele(a) tenta isolá-lo(a) dos seus amigos e família?", context: "O isolamento social é uma tática usada para aumentar o controlo sobre a vítima." },
    { text: "Sente medo de expressar a sua opinião perto dele(a)?", context: "O medo constante pode indicar um relacionamento abusivo." },
    { text: "Ele(a) faz comentários depreciativos sobre si frequentemente?", context: "Comentários negativos constantes podem ser um sinal de manipulação emocional." },
    { text: "Ele(a) verifica o seu telemóvel sem a sua permissão?", context: "A invasão de privacidade pode ser um sinal de controlo excessivo." },
    { text: "Ele(a) ameaça prejudicá-lo(a) de alguma forma se não fizer o que quer?", context: "Ameaças, mesmo subtis, são um grande sinal de perigo." },
    { text: "Já tentou terminar a relação, mas ele(a) não aceitou ou reagiu agressivamente?", context: "Dificuldade em aceitar um fim de relação pode indicar controlo ou posse." },
    { text: "Ele(a) tenta controlar as suas finanças ou impedir que tenha acesso a dinheiro?", context: "O controlo financeiro é uma forma de dependência forçada." },
    { text: "Ele(a) já lhe levantou a mão ou empurrou, mesmo que tenha dito que foi sem querer?", context: "Qualquer forma de agressão física é inaceitável e um sinal claro de abuso." },
    { text: "Ele(a) ignora os seus sentimentos ou desvaloriza as suas preocupações?", context: "A falta de empatia e o desprezo pelos sentimentos do outro podem ser sinais de manipulação emocional." },
    { text: "Ele(a) já lhe proibiu de usar certas roupas ou tentou controlar a sua aparência?", context: "Impor regras sobre a sua aparência pode ser um sinal de controlo emocional." },
    { text: "Ele(a) faz você sentir-se culpado(a) por coisas que não fez?", context: "A manipulação emocional pode incluir a inversão de culpa para controlar a vítima." },
    { text: "Ele(a) já fez chantagem emocional para conseguir o que quer?", context: "A chantagem emocional pode ser um sinal de abuso psicológico." },
    { text: "Ele(a) desvaloriza as suas conquistas ou sucessos?", context: "Diminuir os feitos de alguém pode ser uma tentativa de enfraquecer a sua autoestima." },
    { text: "Ele(a) já fez pressão para que tenha relações sexuais sem que queira?", context: "Pressão ou coerção sexual são formas de abuso." },
    { text: "Ele(a) ameaça magoar-se se você terminar a relação?", context: "Ameaças deste tipo são uma tática para prender alguém num relacionamento." },
    { text: "Ele(a) já gritou consigo de forma agressiva ou intimidante?", context: "A intimidação verbal pode ser um tipo de abuso emocional." },
    { text: "Ele(a) já destruiu objetos seus durante uma discussão?", context: "Destruir objetos pode ser um sinal de agressividade e tentativa de intimidação." },
    { text: "Ele(a) exige saber onde está e com quem a toda a hora?", context: "O controlo excessivo sobre os seus movimentos pode ser um sinal de abuso." },
    { text: "Ele(a) já impediu você de sair de casa ou do carro durante uma discussão?", context: "Restringir a sua liberdade de movimento é um sinal de comportamento controlador." }
];
